# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chkcerts < Formula
  desc "Display and validate TLS certificate chains from the command line"
  homepage "https://github.com/chris-short/chkcerts"
  version "0.20260627.25"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chris-short/chkcerts/releases/download/v0.20260627.25/chkcerts_Darwin_x86_64.tar.gz"
      sha256 "cd63c4ab57d11d7a23b6a2c4fd2ff72d225ef95c1bab2edf7e3b8f0d523b3044"

      define_method(:install) do
        bin.install "chkcerts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chris-short/chkcerts/releases/download/v0.20260627.25/chkcerts_Darwin_arm64.tar.gz"
      sha256 "4efd0ca260906b13d1f90f672f125c6ac35538348545a365c998f0c164426742"

      define_method(:install) do
        bin.install "chkcerts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chris-short/chkcerts/releases/download/v0.20260627.25/chkcerts_Linux_x86_64.tar.gz"
      sha256 "743fa8320e0127b230995362b3f3d549594100bb14b980994d6b54f46a98cb73"
      define_method(:install) do
        bin.install "chkcerts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chris-short/chkcerts/releases/download/v0.20260627.25/chkcerts_Linux_arm64.tar.gz"
      sha256 "1e5a621a825b149e0c9798271bd0bfa395f578fbe39cca057bc0602e2892cb0b"
      define_method(:install) do
        bin.install "chkcerts"
      end
    end
  end

  test do
    system "#{bin}/chkcerts", "https://github.com"
  end
end
