# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chkcerts < Formula
  desc "Display and validate TLS certificate chains from the command line"
  homepage "https://github.com/chris-short/chkcerts"
  version "0.20260627.26"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chris-short/chkcerts/releases/download/v0.20260627.26/chkcerts_Darwin_x86_64.tar.gz"
      sha256 "c6be5b387947ae5ebf090f78d8c0e0d8306e11bcf86cc0cf8ef7687c3dfac9cb"

      define_method(:install) do
        bin.install "chkcerts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chris-short/chkcerts/releases/download/v0.20260627.26/chkcerts_Darwin_arm64.tar.gz"
      sha256 "b70816dc9b2fd182ada8b2d8bf55da1b70f250f07849d40ab65b58f7397953a7"

      define_method(:install) do
        bin.install "chkcerts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chris-short/chkcerts/releases/download/v0.20260627.26/chkcerts_Linux_x86_64.tar.gz"
      sha256 "ec7c6e881423795c2270966199adc28a7a952f9ad60b64364f980492aec17361"
      define_method(:install) do
        bin.install "chkcerts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chris-short/chkcerts/releases/download/v0.20260627.26/chkcerts_Linux_arm64.tar.gz"
      sha256 "83333d0e157295094e1d118ac3b4f8acb052a99fa1dfa147f51e2046f7de6748"
      define_method(:install) do
        bin.install "chkcerts"
      end
    end
  end

  test do
    system "#{bin}/chkcerts", "https://github.com"
  end
end
